### PR TITLE
Sound-supervisor would not build

### LINKED ISSUE #697: Sound supervisor npm build will fail
**Describe the problem**
Install latest build, sound supervisor will be on an endless loop due to the removed COPY VERSION from the latest commit. 

**To Reproduce**
Just start iotsound

sound-supervisor  npm ERR! code ELIFECYCLE
 sound-supervisor  npm ERR! errno 1
 sound-supervisor  npm ERR! sound-supervisor@1.0.1 start: node build/index.js
 sound-supervisor  npm ERR! Exit status 1
 sound-supervisor  npm ERR! 
 sound-supervisor  npm ERR! Failed at the sound-supervisor@1.0.1 start script.
 sound-supervisor  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 sound-supervisor  
 sound-supervisor  npm ERR! A complete log of this run can be found in:
 sound-supervisor  npm ERR!     /root/.npm/_logs/2025-08-01T17_40_14_958Z-debug.log

Error: ENOENT: no such file or directory, open 'VERSION'
 sound-supervisor      at Object.openSync (fs.js:498:3)
 sound-supervisor      at Object.readFileSync (fs.js:394:35)
 sound-supervisor      at Object.<anonymous> (/usr/src/build/SoundAPI.js:10:20)
 sound-supervisor      at Module._compile (internal/modules/cjs/loader.js:1114:14)
 sound-supervisor      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
 sound-supervisor      at Module.load (internal/modules/cjs/loader.js:979:32)
 sound-supervisor      at Function.Module._load (internal/modules/cjs/loader.js:819:12)
 sound-supervisor      at Module.require (internal/modules/cjs/loader.js:1003:19)
 sound-supervisor      at require (internal/modules/cjs/helpers.js:107:18)
 sound-supervisor      at Object.<anonymous> (/usr/src/build/index.js:5:20) {
 sound-supervisor    errno: -2,
 sound-supervisor    syscall: 'open',
 sound-supervisor    code: 'ENOENT',
 sound-supervisor    path: 'VERSION'
 sound-supervisor  }

**Expected behavior**
Sound supervisor starts

**Device information**
 - Board (hardware info):Raspberry Pi 4 HiFiBerry DAC
 - Device type (as seen in balenaCloud):  Raspberry Pi 4 (using 64bit OS)
 - balenaOS version: 3.11.0+rev3

**Additional context**
See pull request for fix, declared min version, still look for the file in case used in the future, unsure if there is other code dependencies so did not try just removing it. It is tested to build and work appropriately after this change. 

https://github.com/iotsound/iotsound/pull/696

### PR DESCRIPTION
**Pull request by JaragonCR**
Sound supervisor was failing to build due to looking for a VERSION file that was removed with the branding cleanup. Declared a default version of 1.0.1 because I don't know what other applications depend on that version and allowed for this to work in the future if the file is readded.

### CODE REVIEW

**Comment by JaragonCR** [comment]
@vipulgupta2048 @alanb128 any chance you can approve or inspect this PR?

File: core/sound-supervisor/src/SoundAPI.ts [hunk 1]
```diff
@@ -9,7 +9,12 @@ import { restartDevice, rebootDevice, shutdownDevice } from './utils'
 import { getSdk, BalenaSDK } from 'balena-sdk'
 import * as fs from 'fs'
 
-const VERSION = fs.readFileSync('VERSION', 'utf-8')
+let VERSION = '1.0.1';
```
Comment (vipulgupta2048) [inline core/sound-supervisor/src/SoundAPI.ts]: Any reason we are using v1.0.1 here when the file in the past used v3.11.0

https://github.com/iotsound/iotsound/commit/319da73a8847c942b70378914c1cd7ff9e4cef97#diff-7b60b8e351cbb80c47459ffe2c79f1a26404871f49294780fe47ad0e58c09350

File: core/sound-supervisor/src/SoundAPI.ts [hunk 2]
```diff
@@ -9,7 +9,12 @@ import { restartDevice, rebootDevice, shutdownDevice } from './utils'
...
+try {
+  VERSION = fs.readFileSync('VERSION', 'utf8').trim();
+} catch (err) {
+  console.warn('VERSION file not found. Using default version.');
+}
```
Comment (vipulgupta2048) [inline core/sound-supervisor/src/SoundAPI.ts]: Would recommend we use a ternary instead which makes it much cleaner.

```suggestion
const VERSION = fs.existsSync('VERSION') 
  ? fs.readFileSync('VERSION', 'utf8').trim() 
  : '1.0.0'; // or whatever your default version we decide```

**Review by vipulgupta2048 — COMMENTED** [review]
Thanks for your contribution! Two options we can solve this would be, 

1. Merge the PR as it is with a constant version in place
2. Bring back the VERSION file and create workflows that still follow the sematic versioning in place which increments the version for new updates.

File: core/sound-supervisor/src/SoundAPI.ts (hunk 1 above)
Comment (JaragonCR) [reply core/sound-supervisor/src/SoundAPI.ts]: @vipulgupta2048 the error had the SS claiming to be 1.0.1 didn't want to create more issues since I did not fully inspect the code, it seems 1.0.1 is doing the trick just fine so I did not test any other variables. 

sound-supervisor npm ERR! code ELIFECYCLE sound-supervisor npm ERR! errno 1 sound-supervisor npm ERR! sound-supervisor@1.0.1 start: node build/index.js sound-supervisor npm ERR! Exit status 1 sound-supervisor npm ERR! sound-supervisor npm ERR! Failed at the sound-supervisor@1.0.1 start script. sound-supervisor npm ERR! This is probably not a problem with npm. There is likely additional logging output above. sound-supervisor sound-supervisor npm ERR! A complete log of this run can be found in: sound-supervisor npm ERR! /root/.npm/_logs/2025-08-01T17_40_14_958Z-debug.log

File: core/sound-supervisor/src/SoundAPI.ts (hunk 2 above)
Comment (JaragonCR) [reply core/sound-supervisor/src/SoundAPI.ts]: this seems much more elegant yes, this way the variable is locked after start and avoids any other issues.   We would delete my let in this scenario, just want to make sure we don't forget it.

File: core/sound-supervisor/src/SoundAPI.ts (hunk 1 above)
Comment (vipulgupta2048) [reply core/sound-supervisor/src/SoundAPI.ts]: From my context, albeit limited too. It would seem that v1.0.1 is the sound supervisor version coming from https://github.com/iotsound/iotsound/blob/352ff3614f255e256ef45dcac3dddff6a351693b/core/sound-supervisor/package.json#L3 in this NPM error. 

Which is different than

The `VERSION` file which was in the root of the repository. Another reason I think it is that version inside that VERSION file because Sound Supervisor couldn't build exactly when the file was deleted. 

Hence, it point to the version being v3.11.0

**Comment by vipulgupta2048** [comment]
Please make the suggested changes and squash the PR to be one commit that could be merged. Thanks!

File: core/sound-supervisor/src/SoundAPI.ts (hunk 1 above)
Comment (JaragonCR) [reply core/sound-supervisor/src/SoundAPI.ts]: Concur now that I read this error and don't need my iotsound read for the pool party in 20 mins :P

**Review by vipulgupta2048 — APPROVED** [review]

**Comment by vipulgupta2048** [comment]
Thanks for your contribution and good luck for next pool party 🎉 
Please do give this a test on your existing setup and see if everything works correctly
